### ISSUE TITLE
Detik API

### ISSUE THREAD

**Issue by fadmastuti** [urbanriskmap/cognicity-reports-detik#2]
Hi @talltom ,
We got the reply from Detik about the API question for Surabaya and Bandung:
Based on the agreement with PetaJakarta last time, they opened their flood report API for us. And it was already for entire Indonesia area, so technically we already got what we just ask now.
They can not clip it based on the cities that are requested, but we can freely do it for our PetaBencana.

If we can not see any reports from Surabaya or Bandung, it could be:
1. there is no flood report on that area
2. we need to refresh our map so that we can get the updated feeds (?)

p.s  I am sorry, I don't understand exactly why we failed to load the data for Bandung and Surabaya since we were accidentally see a report from Kalimantan about 2 months ago.

cc @anexact

**Comment by tomasholderness** [comment]
Hi @fadmastuti thanks for the update. The good news is that @matthewberryman already started running this code to get Deitk reports, and our new database schema automatically filters them by city.

@matthewberryman - I fixed a couple of minor issues in master, please could you deploy when possible. I would also suggest we delete ~~master~~ **dev** branch to avoid confusion as no longer needed, and after review I can confirm that my changes in dev are no good and master is the version we should be using anyway.

**Comment by matthewberryman** [comment]
@talltom running this now. I assume you meant to write to delete dev branch?

**Comment by tomasholderness** [comment]
Great thanks. Yes sorry for the typo! Dev branch is junk.
